# pi_play_record.py
import sounddevice as sd
import numpy as np
import scipy.io.wavfile as wav
import time

def play_and_record(playfile, recfile, record_seconds=6, fs=44100):
    # Read WAV file to play
    fs_play, data = wav.read(playfile)
    if fs_play != fs:
        raise ValueError("Sample rate mismatch")

    print("Starting playback and recording...")

    # Create recording buffer
    recording = sd.rec(int(record_seconds * fs), samplerate=fs, channels=1)
    time.sleep(0.5)  # Small delay before playback

    # Play audio (blocking)
    sd.play(data, fs)
    sd.wait()

    # Wait to finish recording
    sd.wait()

    print("Recording complete, saving file...")
    wav.write(recfile, fs, recording)
    print(f"Saved recorded file: {recfile}")

if __name__ == '__main__':
    playfile = 'sweep_test.wav'      # The file generated by MATLAB
    recfile = 'mic_recording.wav'   # File to save recording

    play_and_record(playfile, recfile)
