# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: video_streaming.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'video_streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15video_streaming.proto\x12\x05video\" \n\nVideoFrame\x12\x12\n\nframe_data\x18\x01 \x01(\x0c\"(\n\x0eStreamResponse\x12\x16\n\x0estatus_message\x18\x01 \x01(\t2M\n\x0eVideoStreaming\x12;\n\x0bStreamVideo\x12\x11.video.VideoFrame\x1a\x15.video.StreamResponse\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIDEOFRAME']._serialized_start=32
  _globals['_VIDEOFRAME']._serialized_end=64
  _globals['_STREAMRESPONSE']._serialized_start=66
  _globals['_STREAMRESPONSE']._serialized_end=106
  _globals['_VIDEOSTREAMING']._serialized_start=108
  _globals['_VIDEOSTREAMING']._serialized_end=185
# @@protoc_insertion_point(module_scope)
